### PR TITLE
Let varnishgather look for the broadcaster

### PR DESCRIPTION
**Pull request by mariusmagureanu**

### CODE REVIEW

**Comment by stone** [comment]
How about doing a "list_packages" and "show_package" for broadcaster? 
Then you will get good solid version information (without actually running broadcaster). 

Also, don't forget to bump the version number.

**Comment by rezan** [comment]
Do you mind if I move the broadcaster version cmd down a few lines? Right now that overtook varnishd as the first file. It might just be me, but the first thing I do in a gather is cat the varnishd version which has always been in position 001.

**Comment by Dridi** [comment]
@rezan, agreed.

**Comment by rezan** [comment]
Fixed https://github.com/varnish/varnishgather/commit/3e2d2132ec96ffc9a4a3ebb1e2eb4a8880aea08b

**Pull request merged**
